Repository LikeLion-at-CAU-10th/Pretty-Lion, pull requests merged in 2022-02, with the labels that each got.

#2 Feat/room
  .gitignore
  PrettyLion/PrettyLion/settings.py
  PrettyLion/__init__.py
  PrettyLion/playground/__init__.py
  PrettyLion/playground/admin.py
  PrettyLion/playground/apps.py
  PrettyLion/playground/constants.py
  PrettyLion/playground/migrations/0001_initial.py
  PrettyLion/playground/migrations/0002_remove_room_mento_room_mentor_alter_room_limit.py
  PrettyLion/playground/migrations/__init__.py
  PrettyLion/playground/models.py
  PrettyLion/playground/tests.py
  PrettyLion/playground/views.py
Labels: enhancement

#13 [FE] refactor: landing page
  PrettyLion/mainboard/static/css/index.css
  PrettyLion/mainboard/static/js/landing.js
  PrettyLion/mainboard/templates/index.html
Labels: refactor

#18 [FE] added rotating values
  PrettyLion/mainboard/static/css/index.css
  PrettyLion/mainboard/static/js/landing.js
  PrettyLion/mainboard/templates/index.html
Labels: feature

#19 [FE] feat: added rotating three values
  PrettyLion/mainboard/static/js/landing.js
Labels: feature

#20 [FE] refactor: edit details
  PrettyLion/mainboard/static/css/index.css
  PrettyLion/mainboard/templates/index.html
Labels: refactor

#21 [FE] feat: aboutus-10th orbiting profiles
  PrettyLion/mainboard/static/css/index.css
  PrettyLion/mainboard/static/js/landing.js
  PrettyLion/mainboard/templates/index.html
Labels: feature

#27 feat: added popping animation for aboutus-10th
  PrettyLion/mainboard/static/js/landing.js
Labels: feature

#34 feat: aboutus-10th add btn added
  PrettyLion/mainboard/static/css/index.css
  PrettyLion/mainboard/static/js/landing.js
  PrettyLion/mainboard/templates/index.html
Labels: feature

#43 refactor: aligned whoweare tab
  PrettyLion/mainboard/static/css/indexBox.css
  PrettyLion/mainboard/static/js/changeBox.js
  PrettyLion/mainboard/templates/index.html
Labels: refactor

#44 refactor: moved aboutus10th from index.html to story.html
  PrettyLion/mainboard/static/css/aboutus10th.css
  PrettyLion/mainboard/static/css/index.css
  PrettyLion/mainboard/static/css/story.css
  PrettyLion/mainboard/static/js/aboutus10th.js
  PrettyLion/mainboard/static/js/landing.js
  PrettyLion/mainboard/templates/index.html
  PrettyLion/mainboard/templates/story.html
Labels: refactor
